# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '꼬끼오톡' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosAssignment1
  pod 'Alamofire'
  pod 'SwiftLint'

end
